"""Move CVs to user profile

Revision ID: 0e32899ab3d2
Revises: 6f83df0ffd96
Create Date: 2026-06-30 09:45:54.850514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e32899ab3d2'
down_revision: Union[str, Sequence[str], None] = '6f83df0ffd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cv_filename')
    op.add_column('users', sa.Column('primary_cv_filename', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('secondary_cv_filename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secondary_cv_filename')
    op.drop_column('users', 'primary_cv_filename')
    op.add_column('applications', sa.Column('cv_filename', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
