"""add application source fields

Revision ID: 6346fd31a4d5
Revises: 0e32899ab3d2
Create Date: 2026-07-03 14:42:55.977449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6346fd31a4d5'
down_revision: Union[str, Sequence[str], None] = '0e32899ab3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'source_url')
    op.drop_column('applications', 'platform')
    # ### end Alembic commands ###
