"""Add cv filename to applications

Revision ID: 6f83df0ffd96
Revises: 92836b944a0d
Create Date: 2026-06-26 20:35:28.868256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f83df0ffd96'
down_revision: Union[str, Sequence[str], None] = '92836b944a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cv_filename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cv_filename')
    # ### end Alembic commands ###
