"""Remove full_name from users

Revision ID: baa666b9a2df
Revises: cc6548df0cd9
Create Date: 2026-06-25 15:53:15.660653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa666b9a2df'
down_revision: Union[str, Sequence[str], None] = 'cc6548df0cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
